refactor: update stack with component-rollup-config
ovh-ux/ng-ovh-form-flat pull request #3
Opened 2019-02-14 19:28 UTC by antleblanc

# Update stack

### 🗜 Refactor

b2e4f91 — refactor: update stack with component-rollup-config

### 💥 Breaking Change

Module is now named as `ngOvhFormFlat`

ref: ovh-ux/manager#192

2019-02-15 09:03 UTC, cbourgois requested changes

2019-02-15 09:03 UTC, cbourgois commented on src/flat-checkbox/index.less
>  @flat-checkbox-width: 18px;
Should be scoped : 

```less 
flat-checkbox, [data-flat-checkbox], [flat-checkbox]
```

2019-02-15 09:03 UTC, cbourgois commented on src/flat-radio/index.less
>  .flat-radio-input-hover {
Should be scoped : 

```less 
flat-radio, [data-flat-radio], [flat-radio]
```

2019-02-15 09:03 UTC, cbourgois commented on src/flat-select/index.less
> +div.flat-select {
Should be scoped : 

```less 
flat-select, [data-flat-select], [flat-select]
```

2019-02-15 09:03 UTC, cbourgois commented on src/flat-switch/index.less
>  .flat-switch {
Should be scoped : 

```less 
flat-switch, [data-flat-switch], [flat-switch]
```

2019-02-15 14:07 UTC, antleblanc commented on src/flat-checkbox/index.less
>  @flat-checkbox-width: 18px;
Variables are used across all `.*less` files.

Styles are already scoped by `.flat-*`.

Your suggestions doesn't work. Did I miss something? Thanks.

2019-02-15 14:07 UTC, antleblanc commented on src/flat-radio/index.less
>  .flat-radio-input-hover {
Please refer to my previous comment.

2019-02-15 14:07 UTC, antleblanc commented on src/flat-select/index.less
> +div.flat-select {
Please refer to my previous comment.

2019-02-15 14:07 UTC, antleblanc commented on src/flat-switch/index.less
>  .flat-switch {
Please refer to my previous comment.

2019-02-15 16:25 UTC, antleblanc commented on src/flat-checkbox/index.less
>  @flat-checkbox-width: 18px;
These selectors can be reached due to the `replace: true`.

2019-02-18 11:59 UTC, cbourgois commented on src/flat-checkbox/index.less
>  @flat-checkbox-width: 18px;
Seems legit.

2019-02-18 13:12 UTC, cbourgois approved these changes

2019-02-18 15:27 UTC, FredericEspiau approved these changes

2019-02-19 13:43 UTC, merged